[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "vite"
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = "dist"
  autoLaunch = true

# Redirect all API requests to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirect all non-file requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200