[build]
  command = "npm run build"
  functions = "dist/functions"
  publish = "public"

[dev]
  framework = "#custom"
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "public"
  autoLaunch = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb"]